services:
  nginx-reverse-emby:
    build:
      context: .
      target: control-plane-runtime
    image: nginx-reverse-emby:local
    container_name: nginx-reverse-emby
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "80:3000"

    environment:
      PANEL_ROLE: master
      PANEL_BACKEND_HOST: 0.0.0.0
      PANEL_BACKEND_PORT: "3000"
      MASTER_LOCAL_AGENT_ENABLED: "0"

      API_TOKEN: change-this-token
      MASTER_REGISTER_TOKEN: change-this-register-token

    volumes:
      - ./data:/opt/nginx-reverse-emby/panel/data
