export { consumeAgentMonitorStream } from './agentMonitor'

// Paginated list APIs live on the real runtime client (T1 control-plane routes).
// Re-export so DEV/prod api/index.js can resolve them by name.
export {
  buildListQueryParams,
  normalizeListPageResponse,
  fetchHttpRulesPage,
  fetchL4RulesPage,
  fetchCertificatesPage,
  fetchRelayListenersPage,
  fetchWireGuardProfilesPage
} from './runtime.js'

export {
  verifyToken,
  fetchSystemInfo,
  exportBackup,
  importBackup,
  exportBackupSelective,
  importBackupPreview,
  fetchBackupResourceCounts,
  fetchAgents,
  updateAgent,
  fetchAgentStats,
  fetchEgressProfiles,
  createEgressProfile,
  updateEgressProfile,
  deleteEgressProfile,
  fetchRules,
  createRule,
  updateRule,
  deleteRule,
  diagnoseRule,
  fetchAgentTask,
  applyConfig,
  deleteAgent,
  renameAgent,
  fetchAllAgentsRules,
  fetchAllAgentsL4Rules,
  checkHealth,
  fetchL4Rules,
  createL4Rule,
  updateL4Rule,
  deleteL4Rule,
  diagnoseL4Rule,
  fetchCertificates,
  createCertificate,
  updateCertificate,
  deleteCertificate,
  issueCertificate,
  fetchAllAgentsCertificates,
  fetchAllAgentsRelayListeners,
  fetchRelayListeners,
  fetchAllRelayListeners,
  createRelayListener,
  updateRelayListener,
  deleteRelayListener,
  fetchWireGuardProfiles,
  createWireGuardProfile,
  updateWireGuardProfile,
  deleteWireGuardProfile,
  fetchWireGuardClients,
  createWireGuardClient,
  updateWireGuardClient,
  deleteWireGuardClient,
  fetchWireGuardClientConfig,
  fetchWireGuardClientURI,
  parseWireGuardURI,
  importWireGuardURIProfile,
  fetchVersionPolicies,
  createVersionPolicy,
  updateVersionPolicy,
  deleteVersionPolicy,
  fetchTrafficPolicy,
  updateTrafficPolicy,
  fetchTrafficSummary,
  fetchTrafficTrend,
  calibrateTraffic,
  cleanupTraffic,
  fetchTrafficOverview,
  fetchTrafficAggregate
} from './devMocks/index.js'
