let implementationPromise

function loadImplementation() {
  if (!implementationPromise) {
    implementationPromise = import.meta.env.DEV
      ? import('./devRuntime.js')
      : import('./runtime.js')
  }
  return implementationPromise
}

// IMPORTANT: use static property access (`m.fetchSystemInfo`) rather than
// dynamic keys (`m[name]`). Production bundlers otherwise tree-shake the
// named exports of the lazily loaded runtime module, leaving
// `implementation[name]` undefined at runtime ("e is not a function").
export const verifyToken = (...args) => loadImplementation().then((m) => m.verifyToken(...args))
export const consumeAgentMonitorStream = (...args) => loadImplementation().then((m) => m.consumeAgentMonitorStream(...args))
export const fetchSystemInfo = (...args) => loadImplementation().then((m) => m.fetchSystemInfo(...args))
export const exportBackup = (...args) => loadImplementation().then((m) => m.exportBackup(...args))
export const importBackup = (...args) => loadImplementation().then((m) => m.importBackup(...args))
export const fetchAgents = (...args) => loadImplementation().then((m) => m.fetchAgents(...args))
export const updateAgent = (...args) => loadImplementation().then((m) => m.updateAgent(...args))
export const fetchAgentStats = (...args) => loadImplementation().then((m) => m.fetchAgentStats(...args))
export const fetchEgressProfiles = (...args) => loadImplementation().then((m) => m.fetchEgressProfiles(...args))
export const createEgressProfile = (...args) => loadImplementation().then((m) => m.createEgressProfile(...args))
export const updateEgressProfile = (...args) => loadImplementation().then((m) => m.updateEgressProfile(...args))
export const deleteEgressProfile = (...args) => loadImplementation().then((m) => m.deleteEgressProfile(...args))
export const fetchRules = (...args) => loadImplementation().then((m) => m.fetchRules(...args))
export const fetchHttpRulesPage = (...args) => loadImplementation().then((m) => m.fetchHttpRulesPage(...args))
export const createRule = (...args) => loadImplementation().then((m) => m.createRule(...args))
export const updateRule = (...args) => loadImplementation().then((m) => m.updateRule(...args))
export const deleteRule = (...args) => loadImplementation().then((m) => m.deleteRule(...args))
export const diagnoseRule = (...args) => loadImplementation().then((m) => m.diagnoseRule(...args))
export const fetchAgentTask = (...args) => loadImplementation().then((m) => m.fetchAgentTask(...args))
export const applyConfig = (...args) => loadImplementation().then((m) => m.applyConfig(...args))
export const deleteAgent = (...args) => loadImplementation().then((m) => m.deleteAgent(...args))
export const renameAgent = (...args) => loadImplementation().then((m) => m.renameAgent(...args))
export const fetchAllAgentsRules = (...args) => loadImplementation().then((m) => m.fetchAllAgentsRules(...args))
export const fetchAllAgentsL4Rules = (...args) => loadImplementation().then((m) => m.fetchAllAgentsL4Rules(...args))
export const checkHealth = (...args) => loadImplementation().then((m) => m.checkHealth(...args))
export const fetchL4Rules = (...args) => loadImplementation().then((m) => m.fetchL4Rules(...args))
export const fetchL4RulesPage = (...args) => loadImplementation().then((m) => m.fetchL4RulesPage(...args))
export const createL4Rule = (...args) => loadImplementation().then((m) => m.createL4Rule(...args))
export const updateL4Rule = (...args) => loadImplementation().then((m) => m.updateL4Rule(...args))
export const deleteL4Rule = (...args) => loadImplementation().then((m) => m.deleteL4Rule(...args))
export const diagnoseL4Rule = (...args) => loadImplementation().then((m) => m.diagnoseL4Rule(...args))
export const fetchCertificates = (...args) => loadImplementation().then((m) => m.fetchCertificates(...args))
export const fetchCertificatesPage = (...args) => loadImplementation().then((m) => m.fetchCertificatesPage(...args))
export const createCertificate = (...args) => loadImplementation().then((m) => m.createCertificate(...args))
export const updateCertificate = (...args) => loadImplementation().then((m) => m.updateCertificate(...args))
export const deleteCertificate = (...args) => loadImplementation().then((m) => m.deleteCertificate(...args))
export const issueCertificate = (...args) => loadImplementation().then((m) => m.issueCertificate(...args))
export const fetchAllAgentsCertificates = (...args) => loadImplementation().then((m) => m.fetchAllAgentsCertificates(...args))
export const fetchAllAgentsRelayListeners = (...args) => loadImplementation().then((m) => m.fetchAllAgentsRelayListeners(...args))
export const fetchRelayListeners = (...args) => loadImplementation().then((m) => m.fetchRelayListeners(...args))
export const fetchRelayListenersPage = (...args) => loadImplementation().then((m) => m.fetchRelayListenersPage(...args))
export const fetchAllRelayListeners = (...args) => loadImplementation().then((m) => m.fetchAllRelayListeners(...args))
export const createRelayListener = (...args) => loadImplementation().then((m) => m.createRelayListener(...args))
export const updateRelayListener = (...args) => loadImplementation().then((m) => m.updateRelayListener(...args))
export const deleteRelayListener = (...args) => loadImplementation().then((m) => m.deleteRelayListener(...args))
export const fetchVersionPolicies = (...args) => loadImplementation().then((m) => m.fetchVersionPolicies(...args))
export const createVersionPolicy = (...args) => loadImplementation().then((m) => m.createVersionPolicy(...args))
export const updateVersionPolicy = (...args) => loadImplementation().then((m) => m.updateVersionPolicy(...args))
export const deleteVersionPolicy = (...args) => loadImplementation().then((m) => m.deleteVersionPolicy(...args))
export const exportBackupSelective = (...args) => loadImplementation().then((m) => m.exportBackupSelective(...args))
export const importBackupPreview = (...args) => loadImplementation().then((m) => m.importBackupPreview(...args))
export const fetchBackupResourceCounts = (...args) => loadImplementation().then((m) => m.fetchBackupResourceCounts(...args))
export const fetchTrafficPolicy = (...args) => loadImplementation().then((m) => m.fetchTrafficPolicy(...args))
export const updateTrafficPolicy = (...args) => loadImplementation().then((m) => m.updateTrafficPolicy(...args))
export const fetchTrafficSummary = (...args) => loadImplementation().then((m) => m.fetchTrafficSummary(...args))
export const fetchTrafficTrend = (...args) => loadImplementation().then((m) => m.fetchTrafficTrend(...args))
export const calibrateTraffic = (...args) => loadImplementation().then((m) => m.calibrateTraffic(...args))
export const cleanupTraffic = (...args) => loadImplementation().then((m) => m.cleanupTraffic(...args))
export const fetchTrafficOverview = (...args) => loadImplementation().then((m) => m.fetchTrafficOverview(...args))
export const fetchTrafficAggregate = (...args) => loadImplementation().then((m) => m.fetchTrafficAggregate(...args))
export const fetchDashboardAttention = (...args) => loadImplementation().then((m) => m.fetchDashboardAttention(...args))
