package protogen

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"go/format"
	"path/filepath"

	"github.com/bufbuild/protocompile"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/types/descriptorpb"
)

var SourceFiles = []string{
	"policy/v1/policy.proto",
	"rpc/v1/plugin.proto",
}

func CompileDescriptorSet(ctx context.Context, sdkRoot string) ([]byte, error) {
	root, err := filepath.Abs(sdkRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve plugin SDK root: %w", err)
	}
	compiler := protocompile.Compiler{
		Resolver:       protocompile.WithStandardImports(&protocompile.SourceResolver{ImportPaths: []string{root}}),
		SourceInfoMode: protocompile.SourceInfoNone,
	}
	files, err := compiler.Compile(ctx, SourceFiles...)
	if err != nil {
		return nil, fmt.Errorf("compile canonical plugin IDL: %w", err)
	}
	set := &descriptorpb.FileDescriptorSet{File: make([]*descriptorpb.FileDescriptorProto, len(files))}
	for index, file := range files {
		set.File[index] = protodesc.ToFileDescriptorProto(file)
	}
	encoded, err := (proto.MarshalOptions{Deterministic: true}).Marshal(set)
	if err != nil {
		return nil, fmt.Errorf("marshal canonical descriptor set: %w", err)
	}
	return encoded, nil
}

func RenderGo(descriptorSet []byte) ([]byte, error) {
	digest := sha256.Sum256(descriptorSet)
	source := fmt.Sprintf(`// Code generated by plugin-sdk/go/protoschema/cmd/generate; DO NOT EDIT.

package protoschema

const CanonicalDescriptorSetSHA256 = %q

const canonicalDescriptorSetBase64 = %q
`, fmt.Sprintf("%x", digest), base64.StdEncoding.EncodeToString(descriptorSet))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated descriptor source: %w", err)
	}
	return formatted, nil
}
