name: nre_client
description: NRE Multi-Platform Client
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  intl: ^0.20.0

  # Windows desktop
  window_manager: ^0.4.3
  tray_manager: ^0.3.2

  # UI
  gap: ^3.0.1

  # Logging
  logger: ^2.5.0

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Network
  dio: ^5.8.0

  # Immutable models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Code generation
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5

  # Windows packaging
  msix: ^3.16.8

flutter:
  uses-material-design: true
