ALTER TABLE rules ADD COLUMN relay_chain TEXT DEFAULT '[]';
ALTER TABLE l4_rules ADD COLUMN relay_chain TEXT DEFAULT '[]';
ALTER TABLE managed_certificates ADD COLUMN usage TEXT DEFAULT 'https';
ALTER TABLE managed_certificates ADD COLUMN certificate_type TEXT DEFAULT 'acme';
ALTER TABLE managed_certificates ADD COLUMN self_signed INTEGER DEFAULT 0;
UPDATE rules SET relay_chain = '[]' WHERE relay_chain IS NULL OR trim(relay_chain) = '';
UPDATE l4_rules SET relay_chain = '[]' WHERE relay_chain IS NULL OR trim(relay_chain) = '';
UPDATE managed_certificates SET usage = 'https' WHERE usage IS NULL OR trim(usage) = '';
UPDATE managed_certificates SET certificate_type = 'acme' WHERE certificate_type IS NULL OR trim(certificate_type) = '';
UPDATE managed_certificates SET self_signed = 0 WHERE self_signed IS NULL;
