package proxyheaders

import (
	"net"
	"net/http"
	"strconv"
	"strings"
)

// Forwarded builds the trusted X-* proxy headers generated by the Agent.
// Callers must remove untrusted inbound copies before applying the result.
func Forwarded(scheme, host, clientAddress string) http.Header {
	return ForwardedWithPort(scheme, host, clientAddress, "")
}

// ForwardedWithPort builds trusted proxy headers while allowing a caller to
// preserve an explicitly observed request URL port when Host omits it.
func ForwardedWithPort(scheme, host, clientAddress, explicitPort string) http.Header {
	values := make(http.Header)
	scheme = strings.ToLower(strings.TrimSpace(scheme))
	if scheme == "" {
		scheme = "http"
	}
	host = strings.TrimSpace(host)
	if host != "" {
		values.Set("X-Forwarded-Host", host)
	}
	if port := forwardedPort(scheme, host, explicitPort); port != "" {
		values.Set("X-Forwarded-Port", port)
	}
	if ip := clientIP(clientAddress); ip != "" {
		values.Set("X-Forwarded-For", ip)
		values.Set("X-Real-IP", ip)
	}
	values.Set("X-Forwarded-Proto", scheme)
	return values
}

func forwardedPort(scheme, host, explicitPort string) string {
	if _, port, err := net.SplitHostPort(host); err == nil && port != "" {
		if value, err := strconv.Atoi(port); err == nil && value >= 1 && value <= 65535 {
			return port
		}
	}
	if value, err := strconv.Atoi(strings.TrimSpace(explicitPort)); err == nil && value >= 1 && value <= 65535 {
		return strconv.Itoa(value)
	}
	if scheme == "https" {
		return "443"
	}
	return "80"
}

func clientIP(address string) string {
	address = strings.TrimSpace(address)
	if ip := net.ParseIP(address); ip != nil {
		return ip.String()
	}
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		return ""
	}
	ip := net.ParseIP(host)
	if ip == nil {
		return ""
	}
	return ip.String()
}
