FROM golang:1.26.4-trixie

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends iproute2 wireguard-tools; \
    rm -rf /var/lib/apt/lists/*

ENV GOCACHE=/tmp/go-build
ENV PATH=/usr/local/go/bin:$PATH
WORKDIR /work
