# .github/workflows/your-workflow-file.yml

name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    # --- 添加下面这个 permissions 块 ---
    permissions:
      contents: read     # 允许检出代码 (read)
      packages: write    # 允许推送 Docker 镜像 (write)
    # -----------------------------------

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ... 后续步骤保持不变 ...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHORT_SHA }}